load:
  - iw-base/modules/udp-discovery
  - ./modules/arduino-control

modules:
  - component: udp-discovery
    priority: -1
    await: connected
    config:
      clientConfig:
        friendlyName: light-control
      requestPort: 6031

  - component: arduino-control
    config:
      port: 0
      memberAddress: 1
      dsPath: light-control/devices/Living Room
      globalPath: light-control/global